/* eslint-disable max-len */
const RecordType = require('../models/record-type');

// From https://en.wikipedia.org/wiki/List_of_DNS_record_types retreived 01/07/2020
const recordTypes = [
  new RecordType('A', 'Address record', 'Returns a 32-bit IPv4 address, most commonly used to map hostnames to an IP address of the host, but it is also used for DNSBLs, storing subnet masks in RFC 1101, etc.'),
  new RecordType('AAAA', 'IPv6 address record', 'Returns a 128-bit IPv6 address, most commonly used to map hostnames to an IP address of the host.'),
  new RecordType('AFSDB', 'AFS database record', 'Location of database servers of an AFS cell. This record is commonly used by AFS clients to contact AFS cells outside their local domain. A subtype of this record is used by the obsolete DCE/DFS file system.'),
  new RecordType('APL', 'Address Prefix List', 'Specify lists of address ranges, e.g. in CIDR format, for various address families. Experimental.'),
  new RecordType('CAA', 'Certification Authority Authorization', 'DNS Certification Authority Authorization, constraining acceptable CAs for a host/domain'),
  new RecordType('CDNSKEY', '', 'Child copy of DNSKEY record, for transfer to parent'),
  new RecordType('CDS', 'Child DS', 'Child copy of DS record, for transfer to parent'),
  new RecordType('CDERT', 'Certificate record', 'Stores PKIX, SPKI, PGP, etc.'),
  new RecordType('CNAME', 'Canonical name record', 'Alias of one name to another: the DNS lookup will continue by retrying the lookup with the new name.'),
  new RecordType('CSYNC', 'Child-to-Parent Synchronization', 'Specify a synchronization mechanism between a child and a parent DNS zone. Typical example is declaring the same NS records in the parent and the child zone'),
  new RecordType('DHCID', 'DHCP identifier', 'Used in conjunction with the FQDN option to DHCP'),
  new RecordType('DLV', 'DNSSEC Lookaside Validation record', 'For publishing DNSSEC trust anchors outside of the DNS delegation chain. Uses the same format as the DS record. RFC 5074 describes a way of using these records.'),
  new RecordType('DNAME', '', 'Alias for a name and all its subnames, unlike CNAME, which is an alias for only the exact name. Like a CNAME record, the DNS lookup will continue by retrying the lookup with the new name.'),
  new RecordType('DNSKEY', 'DNS Key record', 'The key record used in DNSSEC. Uses the same format as the KEY record.'),
  new RecordType('DS', 'Delegation signer', 'The record used to identify the DNSSEC signing key of a delegated zone'),
  new RecordType('HIP', 'Host Identity Protocol', 'Method of separating the end-point identifier and locator roles of IP addresses.'),
  new RecordType('IPSECKEY', 'IPsec Key', 'Key record that can be used with IPsec'),
  new RecordType('KEY', 'Key record', 'Used only for SIG(0) (RFC 2931) and TKEY (RFC 2930). RFC 3445 eliminated their use for application keys and limited their use to DNSSEC. RFC 3755 designates DNSKEY as the replacement within DNSSEC. RFC 4025 designates IPSECKEY as the replacement for use with IPsec.'),
  new RecordType('KX', 'Key Exchanger record', 'Used with some cryptographic systems (not including DNSSEC) to identify a key management agent for the associated domain-name. Note that this has nothing to do with DNS Security. It is Informational status, rather than being on the IETF standards-track. It has always had limited deployment, but is still in use.'),
  new RecordType('LOC', 'Location record', 'Specifies a geographical location associated with a domain name'),
  new RecordType('MX', 'Mail exchange record', 'Maps a domain name to a list of message transfer agents for that domain'),
  new RecordType('NAPTR', 'Naming Authority Pointer', 'Allows regular-expression-based rewriting of domain names which can then be used as URIs, further domain names to lookups, etc.'),
  new RecordType('NS', 'Name server record', 'Delegates a DNS zone to use the given authoritative name servers'),
  new RecordType('NSEC', 'Next Secure record', 'Part of DNSSEC—used to prove a name does not exist. Uses the same format as the (obsolete) NXT record.'),
  new RecordType('NSEC3', 'Next Secure record version 3', 'An extension to DNSSEC that allows proof of nonexistence for a name without permitting zonewalking'),
  new RecordType('NSEC3PARAM', 'NSEC3 parameters', 'Parameter record for use with NSEC3'),
  new RecordType('OPENPGPKEY', 'OpenPGP public key record', 'A DNS-based Authentication of Named Entities (DANE) method for publishing and locating OpenPGP public keys in DNS for a specific email address using an OPENPGPKEY DNS resource record.'),
  new RecordType('PTR', 'PTR Resource Record', ' Pointer to a canonical name. Unlike a CNAME, DNS processing stops and just the name is returned. The most common use is for implementing reverse DNS lookups, but other uses include such things as DNS-SD.'),
  new RecordType('RRSIG', 'DNSSEC signature', 'Signature for a DNSSEC-secured record set. Uses the same format as the SIG record.'),
  new RecordType('RP', 'Responsible Person', 'Information about the responsible person(s) for the domain. Usually an email address with the @ replaced by a .'),
  new RecordType('SIG', 'Signature', 'Signature record used in SIG(0) (RFC 2931) and TKEY (RFC 2930). RFC 3755 designated RRSIG as the replacement for SIG for use within DNSSEC.'),
  new RecordType('SMIMEA', 'S/MIME cert association', 'Associates an S/MIME certificate with a domain name for sender authentication.'),
  new RecordType('SOA', 'Start of [a zone of] authority record', 'Specifies authoritative information about a DNS zone, including the primary name server, the email of the domain administrator, the domain serial number, and several timers relating to refreshing the zone.'),
  new RecordType('SRV', 'Service locator', 'Generalized service location record, used for newer protocols instead of creating protocol-specific records such as MX.'),
  new RecordType('SSHFP', 'SSH Public Key Fingerprint', 'Resource record for publishing SSH public host key fingerprints in the DNS System, in order to aid in verifying the authenticity of the host. RFC 6594 defines ECC SSH keys and SHA-256 hashes. See the IANA SSHFP RR parameters registry for details.'),
  new RecordType('TA', 'DNSSEC Trust Authorities', 'Part of a deployment proposal for DNSSEC without a signed DNS root. See the IANA database and Weiler Spec for details. Uses the same format as the DS record.'),
  new RecordType('TKEY', 'Transaction Key record', 'A method of providing keying material to be used with TSIG that is encrypted under the public key in an accompanying KEY RR.'),
  new RecordType('TLSA', 'TLSA certificate association', 'A record for DANE. RFC 6698 defines "The TLSA DNS resource record is used to associate a TLS server certificate or public key with the domain name where the record is found, thus forming a \'TLSA certificate association\'".'),
  new RecordType('TSIG', 'Transaction Signature', 'Can be used to authenticate dynamic updates as coming from an approved client, or to authenticate responses as coming from an approved recursive name server similar to DNSSEC.'),
  new RecordType('TXT', 'Text record', 'Originally for arbitrary human-readable text in a DNS record. Since the early 1990s, however, this record more often carries machine-readable data, such as specified by RFC 1464, opportunistic encryption, Sender Policy Framework, DKIM, DMARC, DNS-SD, etc.'),
  new RecordType('URI', 'Uniform Resource Identifier', 'Can be used for publishing mappings from hostnames to URIs.'),
];

module.exports = recordTypes;
