name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm ci
    - run: npm run lint
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
    - name: Build the Docker image
      run: |
        tag=bind-ui:$(date +%s)
        docker build . --file Dockerfile --tag $tag
        docker save $tag | gzip > bind-ui.tar.gz
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: bind-ui.tar.gz
        path: bind-ui.tar.gz
